### ISSUE TITLE
Error repositorio

### ISSUE THREAD

**Issue by pablogupi** [Monits/Anviz-Protocol#2]
Hola
Ya no existe el repositorio http://nexus.monits.com/content/repositories/external/ ??
Estoy intentando instalar el pom y tengo un timeout en la conexión. Si intento entrar por el navegador ocurre lo mismo. ¿hay alguna alternativa?
Gracias!!

**Comment by jsotuyod** [comment]
@Krashband temo que no, dicho repositorio no existe más tras el M&A de Monits con MercadoLibre. Muchas de las librerías las republicamos en jcenter / maven central, pero a esta temo que nunca le pudimos dedicar el tiempo hasta ahora.

**Comment by solinad21** [comment]
alguna actualización del tema?

**Comment by jsotuyod** [comment]
@solinad21 no hay novedades ni planes de hacer nada al respecto.

Podés clonar el repositorio y bien usar o disponibilizar vos mismo el artefacto.
